# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c74943b541f418a53904b238cf517652b2427ecec072904a35872a063115c15bd6614f6b176cc2dec75377dd2c1b66e3ce43209c647d2a1d52c2f21e6df5ecd

test:
  secret_key_base: 0757458957450d6216ac7830388cacbec592f62a988b52a18d60ef66a3e1db98d4d304fae5b916284c1efcf7b01f6877a76fc52f9acfe9fdbb82cea671dc0171

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
